version: '3.8'

services:
  qdrant:
    build: .
    container_name: qdrant_custom
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
